* Encoding: UTF-8.
file handle data /name="c:/cc/misc2/extensions/r/stats_bayes_anova/tests".

get file="data/puzzles.sav".
dataset name puzzles.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID
/options comparison=8.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID
/options posteriorindex=3 omitposteriorrandom=yes.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID
/options posteriorindex=3 omitposteriorrandom=no.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID
/options posteriorindex=5.

stats bayes anova dependent=RT indepfixed=shape color indeprandom=ID
/options posteriorindex=3 OMITPOSTERIORRANDOM=NO.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender jobcat  MODELS=ALLWITHMAIN
/OPTIONS   POSTERIORINDEX=3 OMITPOSTERIORRANDOM=YES 
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender jobcat  MODELS=ALLWITHMAIN
/OPTIONS COMPARISON=3  POSTERIORINDEX=3 OMITPOSTERIORRANDOM=YES OMITPOSTERIORRANDOM=YES 
    ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender jobcat  MODELS=ALLWITHMAIN
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender jobcat  MODELS=ALLWITHMAIN
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary  MODELS=ALLWITHMAIN
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPRANDOM=jobcat  MODELS=ALLWITHMAIN
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender educ minority INDEPRANDOM=jobcat gender MODELS=STEPUP    
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender educ minority INDEPRANDOM=jobcat  MODELS=STEPUP    
/OPTIONS COMPARISON=3  OMITPOSTERIORRANDOM=YES ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" 
/SAVE WORKSPACE=CLEAR.

string g(a1).
compute g = gender.
compute mu=minority.
variable level mu(nominal).

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=g mu  INDEPRANDOM=jobcat  MODELS=STEPDOWN
/OPTIONS  POSTERIORINDEX=3 OMITPOSTERIORRANDOM=NO ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="WIDE" PRIORSCALERANDOM="WIDE" 
/SAVE WORKSPACE=CLEAR.

compute sig2=minority.
variable level sig2(nominal).

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=g sig2  INDEPRANDOM=jobcat  MODELS=STEPDOWN
/OPTIONS  POSTERIORINDEX=3 OMITPOSTERIORRANDOM=NO ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="WIDE" PRIORSCALERANDOM="WIDE" 
/SAVE WORKSPACE=CLEAR.

STATS BAYES ANOVA DEPENDENT=salary INDEPFIXED=gender minority jobcat  MODELS=ALLWITHMAIN
/OPTIONS  POSTERIORINDEX=3 OMITPOSTERIORRANDOM=NO ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="WIDE" PRIORSCALERANDOM="WIDE" 
/SAVE WORKSPACE=CLEAR.

DATASET ACTIVATE puzzles.
STATS BAYES ANOVA DEPENDENT=RT INDEPFIXED=color shape INDEPRANDOM=ID  MODELS=ALLWITHMAIN
/OPTIONS  ITERATIONS=1000 PLOTMODELS=NO
PRIORSCALEFIXED="MEDIUM" PRIORSCALERANDOM="MEDIUM" BAYESFACTORITERATIONS=20000
/SAVE WORKSPACE=CLEAR.
